"""Write oauth2-proxy's config from the ENTRA_* values in .env.

    python scripts\\build_oauth2_proxy_config.py            # writes deploy/sso/oauth2-proxy.cfg
    python scripts\\build_oauth2_proxy_config.py --check    # validates only, writes nothing

The Entra details live in .env only; this is the one place they are turned into proxy
settings, so the proxy and the app can never disagree. The written file holds the client
secret and is git-ignored. Re-run it after changing any ENTRA_* / SSO_* value, then restart
oauth2-proxy (`oauth2-proxy --config=deploy/sso/oauth2-proxy.cfg`).

Exits 1, naming every problem, instead of writing a config the proxy would reject at
sign-in time.
"""
import argparse
import base64
import binascii
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config.settings import ConfigurationError, Settings, get_settings  # noqa: E402

OUTPUT = Path(__file__).resolve().parent.parent / "deploy" / "sso" / "oauth2-proxy.cfg"
CALLBACK_PATH = "/oauth2/callback"
_GUID_RE = re.compile(r"^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$")
_TENANT_DOMAIN_RE = re.compile(r"^[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+$")
_AES_KEY_BYTES = (16, 24, 32)


def _cookie_secret_ok(secret: str) -> bool:
    # oauth2-proxy accepts the value as base64 of an AES key, or as the raw key itself.
    if len(secret.encode()) in _AES_KEY_BYTES:
        return True
    try:
        decoded = base64.urlsafe_b64decode(secret + "=" * (-len(secret) % 4))
    except (binascii.Error, ValueError):
        return False
    return len(decoded) in _AES_KEY_BYTES


def problems(settings: Settings) -> list[str]:
    found = [f"{name} is empty in .env" for name in settings.entra_missing()]
    tenant, client = settings.ENTRA_TENANT_ID, settings.ENTRA_CLIENT_ID
    if tenant and not (_GUID_RE.match(tenant) or _TENANT_DOMAIN_RE.match(tenant)):
        found.append(f"ENTRA_TENANT_ID '{tenant}' is neither a GUID (Directory (tenant) ID) "
                     "nor a domain such as contoso.onmicrosoft.com")
    if client and not _GUID_RE.match(client):
        found.append(f"ENTRA_CLIENT_ID '{client}' is not a GUID - copy the Application "
                     "(client) ID from the Entra app registration's Overview page")
    if settings.ENTRA_CLIENT_SECRET and _GUID_RE.match(settings.ENTRA_CLIENT_SECRET):
        found.append("ENTRA_CLIENT_SECRET looks like a GUID - that is the Secret ID column. "
                     "Use the Value column (shown once, when the secret was created)")
    uri = settings.ENTRA_REDIRECT_URI
    if uri:
        parsed = urlparse(uri)
        if parsed.scheme not in ("http", "https") or not parsed.netloc:
            found.append(f"ENTRA_REDIRECT_URI '{uri}' is not a full URL")
        elif parsed.path.rstrip("/") != CALLBACK_PATH:
            found.append(f"ENTRA_REDIRECT_URI must end in {CALLBACK_PATH} (oauth2-proxy's "
                         f"callback), got path '{parsed.path}'")
    if settings.SSO_COOKIE_SECRET and not _cookie_secret_ok(settings.SSO_COOKIE_SECRET):
        found.append("SSO_COOKIE_SECRET must be 16, 24 or 32 bytes. Generate one: "
                     "python -c \"import secrets; print(secrets.token_hex(16))\"")
    return found


def render(settings: Settings) -> str:
    def q(value: str) -> str:  # a TOML basic string
        return json.dumps(value)

    https = urlparse(settings.ENTRA_REDIRECT_URI).scheme == "https"
    domains = ", ".join(q(d) for d in settings.sso_email_domains)
    return f"""# GENERATED by scripts/build_oauth2_proxy_config.py from .env - do not edit here.
# Holds the Entra client secret: git-ignored, never copy it into a chat or a ticket.

http_address = "0.0.0.0:4180"
reverse_proxy = true

provider = "oidc"
provider_display_name = "Microsoft Entra ID"
oidc_issuer_url = {q(settings.entra_issuer_url)}
client_id = {q(settings.ENTRA_CLIENT_ID)}
client_secret = {q(settings.ENTRA_CLIENT_SECRET)}
redirect_url = {q(settings.ENTRA_REDIRECT_URI)}
scope = "openid email profile"
# Entra does not send email_verified; without this every sign-in is refused.
insecure_oidc_allow_unverified_email = true

email_domains = [{domains}]

cookie_secret = {q(settings.SSO_COOKIE_SECRET)}
cookie_secure = {"true" if https else "false"}
cookie_expire = "{settings.SESSION_TIMEOUT_MINUTES}m"

# auth_request mode: oauth2-proxy only answers "signed in or not"; nginx proxies the app.
upstreams = ["static://202"]
skip_provider_button = true

# Required by the app - see deploy/sso/nginx_sso.conf.
set_xauthrequest = true
set_authorization_header = true
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="validate only, write nothing")
    args = parser.parse_args()
    try:
        settings = get_settings()
    except ConfigurationError as exc:
        print(exc)
        return 1

    found = problems(settings)
    if found:
        print("Cannot build the oauth2-proxy config - fix these in .env:")
        for problem in found:
            print(f"  - {problem}")
        return 1
    print(f"Entra tenant {settings.ENTRA_TENANT_ID}, client {settings.ENTRA_CLIENT_ID}, "
          f"callback {settings.ENTRA_REDIRECT_URI}, domains {settings.sso_email_domains}")
    if settings.ENTRA_REDIRECT_URI.startswith("http://"):
        print("  WARNING: the redirect URI is http - Entra accepts http only for localhost, "
              "and the proxy cookie will not be marked Secure.")
    if args.check:
        print("OK - nothing written (--check).")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(settings), encoding="utf-8")
    print(f"Wrote {OUTPUT}. Restart oauth2-proxy with --config pointing at it.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
